language: php
php:
  - 5.5
env:
  global:
    - GIT_NAME: "'AGCO-SA API docs site auto deploy'"
    - GIT_EMAIL: leonardocesar91@gmail.com
    - secure: e3k4ATrI1Kn9ap+csIXAQRCSoW+Je9Lm2ElrGahhtA8MAbav+MaRXGKuvzFWaQiwHOSnCvqmGEZL4w4RvIe6kRxd9smPj3gsEdo7nnxvCt57BSCibq0EsxfJQ0/NgVEwApaTdPGhJUu6s46Bv1KtQZ3UhvG0FvpTd/wRF7Vrn
0hjOC1axW9tdzo8+ojChPoKVbT7d6x2j91gXRAsbxckwKpXitobQ73H0FcZ1toeZX5SKt49AWrEPQWXTWRT3w4fJMIYsTXTcHpwnVFD4OI6VYZUiS75lvDXpFoqYaXKeR0MUdZb9PuNtYqUCIpeE3yuLi7jGUIjaV7MYfc5wY6bwTG8aSWS/
oLgxtUgBtuIPItEWtgb+AT2W6IxiwL2g4TWZmo8mCEtQlLlTgSE+ayIIBvmcIQUt2B8gLvTy5YEfGNtatLhzZyHZFXZ94Zh4YjS2qthcifFxZRCWDuc0U6GcQ1T/lV94+9gr3N6SlyMn2etx1Qe83XsiIQ7wGC5VFqWlFcNbR0PibA67Xcr3
xoCf33wQKUjygIm3CMcZBOiChwSZNlbgyplNLRsGgl5pg+GxmrIt7AyijNGcSvzyKiJng2+EN8R6AmGuHUIcgzaCjLdqcyOlvt0qy0+hbM3u9hV/33cGVt7Gpt/uwZr02z9fMDci0ZxXhHixogHLpG9v88=
    - GH_REF: github.com/agco-sa/agco-sa.github.io
#   - GIT_EMAIL: eduardo.bobsin@gmail.com
#   - secure: FGeY3Duhe2XWp4/VWkZzM4ER+qK2ghhb9seuwUiMgE6WUDJz7XuTY0oCn/L96KqvQPOp4LGJ89wPRBjM2JHN/1gjqrINalp3towEu9sS9aA035pRaBHCIW401isKZYiErb18sAN9tU3FBeEzAwbX5X9gaZrWzvl98fiR3XnPpso/qku6ZaN5lGYlNc2E8Iu0RPA4Hkj51ocPOBH4lYjygjkj0yDvMD3H9G/NotUlxEpworsowvmkoakmcApULMirGcuO2XfBGQ1TH+9NzuEPGkZsCb/kgv/C+Gux/aJ5lHhMN+bwB5lk5xxeT2Rup8sVJctZzVEs0nhZRcRcs9LxWR5ALejUssOz4FuSYb2vlrqDme71CHhqjVg+cdYhtQH71n8xud41CLhdIB1b0GEBYkV1X++IBhN+VUxUuecke5ny/LNevIVhWFnKaLFFDmvnnvIV2583YKQ7qfaxQWgudUsnYHCf0WGkK2zDN7f1jO6ZtL48XSszGcMd//dl/Xga7wadrywjn9uhM5FmTIbD9jSHaZPz/TIQySSE/53ryc3WruW8TGeYErl7VEQVD5Wo0FWxyyBlq1Cg8E6vGwu0LN9rZhgik2NCbCg0buogMd3FNv84TUkTlBAm+m5wkw0omy3LRSAGqccphKfOfjv8RQJlxlnIxS4jfgRDlKL09zk=

before_script:
  - composer install --no-progress
script:
  #- vendor/bin/couscous generate -vvv
  - vendor/bin/couscous travis-auto-deploy --php-version=5.5 -vvv
  
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
#  local_dir: .couscous/generated
#  on:
    #branch: master
#    repo: $GH_REF
#    target_branch: master
